#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

import pypandoc


if __name__ == "__main__":
    # pandoc resolves \input relative to the working directory
    os.chdir("tex")
    pypandoc.convert_file(
        "cv.tex",
        "gfm",
        outputfile="../README.md",
        extra_args=["-s", "--template=template.markdown"],
    )
    os.chdir("..")

    with open("README.md", "r") as f:
        lines = f.read().splitlines()

    results = []
    prev = ""
    for line in lines:
        if line.startswith("=") or line.startswith("<span> ="):
            continue
        if line.startswith("**") and prev == "":
            parts = line.split("**")
            if not parts[1].startswith("Foreman-Mackey"):
                results += ["## " + parts[1], ""] + parts[2:]
                continue
        results.append(line)
        prev = line.strip()

    with open("README.md", "w") as f:
        f.write("\n".join(results))
