#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import json
import importlib.util
from datetime import date
from operator import itemgetter

here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "utf8totex", os.path.join(here, "utf8totex.py")
)
utf8totex = importlib.util.module_from_spec(spec)
spec.loader.exec_module(utf8totex)

JOURNAL_MAP = {
    "arxiv e-prints": "ArXiv",
    # "Monthly Notices of the Royal Astronomical Society": "\\mnras",
    # "The Astrophysical Journal": "\\apj",
    # "The Astronomical Journal": "\\aj",
    # "Publications of the Astronomical Society of the Pacific": "\\pasp",
    "iau general assembly": "IAU",
    "american astronomical society meeting abstracts": "AAS",
}


def format_pub(args):
    ind, pub = args
    fmt = "\\item[{{\\color{{numcolor}}\\scriptsize{0}}}] ".format(ind)

    # Hack: Handle missing hyphens
    pub["authors"] = [
        a.replace("Foreman Mackey", "Foreman-Mackey") for a in pub["authors"]
    ]

    n = [
        i
        for i in range(len(pub["authors"]))
        if "Foreman-Mackey, D" in pub["authors"][i]
    ][0]
    pub["authors"][n] = "\\textbf{Foreman-Mackey, Daniel}"
    if len(pub["authors"]) > 5:
        fmt += "; ".join(pub["authors"][:4])
        fmt += "; \\etal"
        if n >= 4:
            fmt += "\\ (incl.\\ \\textbf{DFM})"
    elif len(pub["authors"]) > 1:
        fmt += "; ".join(pub["authors"][:-1])
        fmt += "; \\& " + pub["authors"][-1]
    else:
        fmt += pub["authors"][0]

    fmt += ", {0}".format(pub["year"])

    if pub["doi"] is not None:
        fmt += ", \\doi{{{0}}}{{{1}}}".format(pub["doi"], pub["title"])
    else:
        fmt += ", " + pub["title"]

    if not pub["pub"] in [None, "ArXiv e-prints"]:
        fmt += ", " + JOURNAL_MAP.get(
            pub["pub"].strip("0123456789# ").lower(), pub["pub"]
        )

    if pub["volume"] is not None:
        fmt += ", \\textbf{{{0}}}".format(pub["volume"])

    if pub["page"] is not None:
        fmt += ", {0}".format(pub["page"])

    if pub["arxiv"] is not None:
        fmt += " (\\arxiv{{{0}}})".format(pub["arxiv"])

    if pub["citations"] > 1:
        fmt += " [\\href{{{0}}}{{{1} citations}}]".format(pub["url"], pub["citations"])

    return fmt


def format_repo(repo):
    repo = repo["node"]
    for k in ["name", "description"]:
        repo[k] = utf8totex.utf8totex(repo[k])
    txt = "\\item \\href{{{repo[url]}}}{{{{\\bf {repo[name]}}}}} --- "
    txt += "{repo[stargazers][totalCount]} stars / "
    txt += "{repo[forkCount]} forks \\\\\n"
    txt += "{repo[description]} "
    txt += "\\href{{{repo[homepageUrl]}}}{{[docs]}}"
    txt = txt.format(repo=repo)
    return txt


if __name__ == "__main__":
    with open("data/pubs.json", "r") as f:
        pubs = json.load(f)
    with open("data/other_pubs.json", "r") as f:
        other_pubs = json.load(f)
    with open("data/select_pubs.json", "r") as f:
        select_pubs = json.load(f)
    for p in other_pubs:
        for p1 in pubs:
            if (p1["arxiv"] is not None and p["arxiv"] == p1["arxiv"]) or p[
                "title"
            ] == p1["title"]:
                p["citations"] = max(p["citations"], p1["citations"])
                pubs.remove(p1)
    pubs = sorted(pubs + other_pubs, key=itemgetter("pubdate"), reverse=True)
    pubs = [
        p
        for p in pubs
        if (
            p["doctype"] in ["article", "eprint"]
            and p["pub"] != "Zenodo Software Release"
        )
    ]
    ref = [p for p in pubs if p["doctype"] == "article"]
    unref = [p for p in pubs if p["doctype"] == "eprint"]

    # Compute citation stats
    npapers = len(ref)
    nfirst = sum(1 for p in pubs if "Foreman-Mackey" in p["authors"][0])
    cites = sorted((p["citations"] for p in pubs), reverse=True)
    ncitations = sum(cites)
    hindex = sum(c >= i for i, c in enumerate(cites))

    summary = (
        "refereed: {1} / first author: {2} / citations: {3:,} / " "h-index: {4} ({0})"
    ).format(date.today(), npapers, nfirst, ncitations, hindex)
    with open("tex/pubs_summary.tex", "w") as f:
        f.write(summary)

    macros = [
        f"\\newcommand{{\\pubsdate}}{{{date.today()}}}",
        f"\\newcommand{{\\pubsnumber}}{{{npapers}}}",
        f"\\newcommand{{\\pubscitations}}{{{ncitations:,}}}",
        f"\\newcommand{{\\pubshindex}}{{{hindex}}}",
    ]
    with open("tex/pubs_summary_macros.tex", "w") as f:
        f.write("\n".join(macros))

    ref = list(map(format_pub, zip(range(len(ref), 0, -1), ref)))
    unref = list(map(format_pub, zip(range(len(unref), 0, -1), unref)))
    with open("tex/pubs_ref.tex", "w") as f:
        f.write("\n\n".join(ref))
    with open("tex/pubs_unref.tex", "w") as f:
        f.write("\n\n".join(unref))

    # Choose the selected publications
    selected = []
    for s in select_pubs:
        k = s["key"]
        v = s["value"]
        for doc in pubs:
            if doc[k] == v:
                selected.append(doc)
                break
    selected = sorted(selected, key=itemgetter("pubdate"), reverse=True)
    selected = list(map(format_pub, zip(range(len(selected), 0, -1), selected)))
    with open("tex/pubs_select.tex", "w") as f:
        f.write("\n\n".join(selected))

    # Write the repo info
    with open("data/repos.json", "r") as f:
        repos = json.load(f)
    repos = repos["data"]["user"]["pinnedItems"]["edges"]
    with open("tex/repos.tex", "w") as f:
        f.write("\n\n".join(map(format_repo, repos)))
