name: Auto update

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: actions/cache@v6
        with:
          path: |
            cache/Tectonic/*
            !cache/Tectonic/formats
          key: tectonic-cache-${{ github.sha }}
          restore-keys: |
            tectonic-cache-
      - name: Update publication list
        run: uv run make
        env:
          ADS_DEV_KEY: ${{secrets.ADS_DEV_KEY}}
          GITHUB_API_KEY: ${{secrets.GH_API_KEY}}
      - name: Push updated data files
        continue-on-error: true
        run: |
          git add .
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating data"
          git push https://github.com/$GITHUB_REPOSITORY
      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.16.8
      - name: Compile
        run: |
          ./scripts/compile
          mkdir -p results
          cp tex/*.pdf results
        env:
          XDG_CACHE_HOME: cache
      - name: Push documents
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: results
          target-folder: tex
          branch: main-pdf
          commit-message: "updating pdfs"
          clean: true
          single-commit: true
